[alembic]
script_location = alembic
sqlalchemy-url = postgresql+asyncpg://cbs:cbs_dev@localhost:5432/corebanking

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
console = stream_handler

[formatters]
generic = generic

[logger_root]
level = WARN
handlers = console

[logger_sqlalchemy]
level = WARN
handlers = console
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers = console
qualname = alembic

[handler_console]
class = stream_handler
args = (sys.stdout,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
