#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""The program source for migrations."""
import alembic
from alembic import op
import sqlalchemy as sa
${imports}

# revision identifiers, used by Alembic.
revision = ${up_revision}
down_revision = ${down_revision}
branch_labels = ${branch_labels}
depends_on = ${depends_on}

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    ${upgrades}
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    ${downgrades}
    # ### end Alembic commands ###
